### ISSUE TITLE
How to view training set images

### ISSUE THREAD

**Issue by MRLQ-Q** [ozcelikfu/brain-diffuser#11]
Hello, I am very interested in your research. Congratulations on your article being accepted. I have some questions to ask. For example: 1. How to display the original images of the training set? I trained the results but couldn't compare them with the original image because I didn't know where to find the original image

Looking forward to your answer.

**Comment by ozcelikfu** [comment]
Hi,

You can use the PIL library's PIL.Image option to display images from the prepared files (e.g. "processed_data/subj{:02d}/nsd_test_stim_sub{}.npy") after running prepare_nsddata.py

**Comment by MRLQ-Q** [comment]
> 你好，
> 
> 运行prepare_nsddata.py后，您可以使用PIL库的PIL.Image选项显示准备好的文件中的图像（例如“processed_data/subj{:02d}/nsd_test_stim_sub{}.npy”）

Thank you very much for your reply, but I have tried your suggestion. This shows the FMRI image or the image after stimulation. I saw that your paper contains the original image of the NSD dataset, so I also want to display the original train image of the NSD dataset.
Please let me know. Thank you very much.
