### ISSUE TITLE
How to select average users for image reconstruction

### ISSUE THREAD

**Issue by MRLQ-Q** [ozcelikfu/brain-diffuser#15]
Hi, author：
        I see that your article not only performs user (1, 2, 5, 7), but also performs 'average_user' image reconstruction. But there is no 'average_user' processing found in your code and it is also not found 'average_user' in the NSD dataset . How should this 'average_user' processing be set?
        Looking forward to your answer. Thank you very much.
Your fans

**Comment by ozcelikfu** [comment]
Hi @MRLQ-Q , 'average_user' means latent values of (1,2,5,7) are averaged and then fed to the networks
