### ISSUE TITLE
Conda environment installation failed

### ISSUE THREAD

**Issue by Jefferyy-Peng** [ozcelikfu/brain-diffuser#6]
I'm using conda 23.5.2

When I run the command in anaconda prompt, I got this error: 
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - lcms2==2.12=h3be6417_0
  - nbconvert==6.4.4=py38h06a4308_0
  - colorama==0.4.5=py38h06a4308_0
  - certifi==2022.9.24=py38h06a4308_0
  - libtiff==4.4.0=hecacb30_2
  - pytz==2022.1=py38h06a4308_0
  - lerc==3.0=h295c915_0
  - urllib3==1.26.12=py38h06a4308_0
  - glib==2.69.1=h4ff587b_1
  - chardet==4.0.0=py38h06a4308_1003
  - python==3.8.13=h12debd9_0
  - nbformat==5.3.0=py38h06a4308_0
  - beautifulsoup4==4.11.1=py38h06a4308_0
  - libxslt==1.1.35=h4e12654_0
  - gnutls==3.6.15=he1e5248_0
  - brotlipy==0.7.0=py38h27cfd23_1003
  - astroid==2.11.7=py38h06a4308_0
  - gmp==6.2.1=h295c915_3
  - mkl_fft==1.3.1=py38hd3c417c_0
  - numexpr==2.8.4=py38he184ba9_0
  - pylint==2.14.5=py38h06a4308_0
  - wrapt==1.14.1=py38h5eee18b_0
  - cryptography==38.0.1=py38h9ce1e76_0
  - libiconv==1.16=h7f8727e_2
  - tk==8.6.12=h1ccaba5_0
  - mkl_random==1.2.2=py38h51133e4_0
  - black==22.6.0=py38h06a4308_0
  - gst-plugins-base==1.14.0=h8213a91_2
  - idna==3.4=py38h06a4308_0
  - ujson==5.4.0=py38h6a678d5_0
  - nbclient==0.5.13=py38h06a4308_0
  - nettle==3.7.3=hbbd107a_1
  - numpydoc==1.4.0=py38h06a4308_0
  - intel-openmp==2021.4.0=h06a4308_3561
  - cffi==1.15.1=py38h74dc2b5_0
  - bzip2==1.0.8=h7b6447c_0
  - mkl-service==2.4.0=py38h7f8727e_0
  - entrypoints==0.4=py38h06a4308_0
  - requests==2.28.1=py38h06a4308_0
  - zstd==1.5.2=ha4553b6_0
  - freetype==2.12.1=h4a9f257_0
  - libsodium==1.0.18=h7b6447c_0
  - mkl==2021.4.0=h06a4308_640
  - pyrsistent==0.18.0=py38heee7806_0
  - mypy_extensions==0.4.3=py38h06a4308_1
  - joblib==1.1.1=py38h06a4308_0
  - watchdog==2.1.6=py38h06a4308_0
  - fftw==3.3.9=h27cfd23_1
  - qtconsole==5.3.2=py38h06a4308_0
  - ld_impl_linux-64==2.38=h1181459_1
  - inflection==0.5.1=py38h06a4308_0
  - xz==5.2.6=h5eee18b_0
  - qtwebkit==5.212=h4eab89a_4
  - jellyfish==0.9.0=py38h7f8727e_0
  - bottleneck==1.3.5=py38h7deecbd_0
  - gstreamer==1.14.0=h28cd5cc_2
  - icu==58.2=he6710b0_3
  - giflib==5.2.1=h7b6447c_0
  - libllvm10==10.0.1=hbcb73fb_5
  - pluggy==1.0.0=py38h06a4308_1
  - libpq==12.9=h16c4e8d_3
  - debugpy==1.5.1=py38h295c915_0
  - lz4-c==1.9.3=h295c915_1
  - nest-asyncio==1.5.5=py38h06a4308_0
  - readline==8.2=h5eee18b_0
  - whatthepatch==1.0.2=py38h06a4308_0
  - ca-certificates==2022.10.11=h06a4308_0
  - testpath==0.6.0=py38h06a4308_0
  - ffmpeg==4.3=hf484d3e_0
  - markupsafe==2.1.1=py38h7f8727e_0
  - pyqtwebengine==5.15.7=py38h6a678d5_1
  - typing-extensions==4.3.0=py38h06a4308_0
  - libffi==3.3=he6710b0_2
  - rtree==0.9.7=py38h06a4308_1
  - secretstorage==3.3.1=py38h06a4308_0
  - libwebp-base==1.2.4=h5eee18b_0
  - libgfortran-ng==11.2.0=h00389a5_1
  - pyqt5-sip==12.11.0=py38h6a678d5_1
  - imagesize==1.4.1=py38h06a4308_0
  - lame==3.100=h7b6447c_0
  - wurlitzer==3.0.2=py38h06a4308_0
  - expat==2.4.4=h295c915_0
  - python-lsp-server==1.5.0=py38h06a4308_0
  - libxml2==2.9.14=h74e7548_0
  - spyder==5.3.3=py38h06a4308_0
  - dbus==1.13.18=hb2f20db_0
  - keyring==23.4.0=py38h06a4308_0
  - nspr==4.33=h295c915_0
  - numpy-base==1.23.4=py38h31eccc5_0
  - pathspec==0.9.0=py38h06a4308_0
  - libevent==2.1.12=h8f2d780_0
  - yaml==0.2.5=h7b6447c_0
  - spyder-kernels==2.3.3=py38h06a4308_0
  - qt-webengine==5.15.9=hd2b0992_4
  - typing_extensions==4.3.0=py38h06a4308_0
  - mistune==0.8.4=py38h7b6447c_1000
  - libstdcxx-ng==11.2.0=h1234567_1
  - fontconfig==2.13.1=h6c09931_0
  - libgcc-ng==11.2.0=h1234567_1
  - openh264==2.1.1=h4ff587b_0
  - pysocks==1.7.1=py38h06a4308_0
  - sphinx==5.0.2=py38h06a4308_0
  - tomlkit==0.11.1=py38h06a4308_0
  - libunistring==0.9.10=h27cfd23_0
  - libgfortran5==11.2.0=h1234567_1
  - libpng==1.6.37=hbc83047_0
  - pandas==1.5.1=py38h417a72b_0
  - scikit-learn==1.1.3=py38h6a678d5_0
  - libxcb==1.15=h7f8727e_0
  - lazy-object-proxy==1.6.0=py38h27cfd23_0
  - libtasn1==4.16.0=h27cfd23_0
  - docutils==0.18.1=py38h06a4308_3
  - openssl==1.1.1s=h7f8727e_0
  - pcre==8.45=h295c915_0
  - zlib==1.2.13=h5eee18b_0
  - numpy==1.23.4=py38h14f4228_0
  - jsonschema==4.4.0=py38h06a4308_0
  - libxkbcommon==1.0.1=hfa300c1_0
  - zeromq==4.3.4=h2531618_0
  - nss==3.74=h0370c37_0
  - jpeg==9e=h7f8727e_0
  - psutil==5.9.0=py38h5eee18b_0
  - tomli==2.0.1=py38h06a4308_0
  - libuuid==1.0.3=h7f8727e_2
  - libclang==10.0.1=default_hb85057a_2
  - libspatialindex==1.9.3=h2531618_0
  - sip==6.6.2=py38h6a678d5_0
  - pyqt==5.15.7=py38h6a678d5_1
  - python-lsp-black==1.2.1=py38h06a4308_0
  - _openmp_mutex==5.1=1_gnu
  - krb5==1.19.2=hac12032_0
  - qtpy==2.2.0=py38h06a4308_0
  - qt-main==5.15.2=h327a75a_7
  - sqlite==3.39.3=h5082296_0
  - pytorch==1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - ncurses==6.3=h5eee18b_3
  - pillow==9.2.0=py38hace64e9_1
  - libedit==3.1.20210910=h7f8727e_0
  - libgomp==11.2.0=h1234567_1
  - libidn2==2.3.2=h7f8727e_0
  - libdeflate==1.8=h7f8727e_5
  - libwebp==1.2.4=h11a3e52_0
  - cudatoolkit==11.3.1=h2bc3f7f_2
  - jedi==0.18.1=py38h06a4308_1
  - click==8.0.4=py38h06a4308_0

**Comment by happylufei** [comment]
You can create your own environment and install packages gradually, such as installing the correct version of torch first.
