### ISSUE TITLE
KeyError: 'vd'

### ISSUE THREAD

**Issue by Hyh200** [ozcelikfu/brain-diffuser#7]
KeyErroe:'vd' occurs when I run cliptext_extract_features.py. Can anyone help me fix this
![image](https://github.com/ozcelikfu/brain-diffuser/assets/90013078/cb237131-d5c5-4142-aae1-da83dce90842)

**Comment by happylufei** [comment]
Hello, have you run this script file successfully? I'm having various network issues

OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by happylufei** [comment]
I didn't encounter this problem. You can check whether the pretrained models are placed in the correct location.

**Comment by ozcelikfu** [comment]
Also please check if you have the right version of the versatile diffusion model as there have been some critical changes in the past weeks which I didn't adapted brain-diffuser to
